server:
  port: 1203

eureka:
  instance:
    hostname: 116.62.123.174
    instance-id: http://${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://116.62.123.174:1111/eureka/

spring:
  application:
    name: feign-service

hello-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 5000
    MaxAutoRetriesNextServer: 2